gec/urls.py
from django.conf import urls
from django.contrib import admin
from django.urls import path, include
from user_auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_auth.urls')),
    path('mailer/', include('alu_mailer.urls')),
    path('forum/', include('forum.urls')),
    path('api/', include('api_manager.urls')),

]

urls.handler404 = 'user_auth.views.error_404'
urls.handler500 = 'user_auth.views.error_404'

user_auth/urls.py
from django.urls import path,re_path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('login_auth/', views.auth, name='auth'),
    path('logged_in/', views.logged_in, name='log'),
    path('logout/', views.log_out, name='log_out'),
    path('send/', views.send_email, name='send'),
    re_path(r'^profile/(?P<username>\w+)/$', views.profile, name='profile'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user_auth/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
# from image_optimizer.fields import OptimizedImageField


import datetime
from django.core.validators import MaxValueValidator, MinValueValidator


def current_year():
    return datetime.date.today().year


def max_value_current_year(value):
    return MaxValueValidator(current_year())(value)
# Create your models here.

dept_choice = [
    ('GEN', 'General'),
    ('CSE', 'Computer Science And Engineering'),
    ('Arch', 'Architecture'),
    ('ECE', 'Electronics and Communication Engineering'),
    ('PE', 'Production Engineering'),
    ('CHE', 'Chemical Engineering'),
    ('EEE', 'Electrical and Electronics Engineering'),
    ('MEC', 'Mechanical Engineering'),
    ('CE', 'Civil Engineering')
]

course_choice = (
    ('BT', 'B.Tech'),
    ('MT', 'M.Tech'),
    ('S', 'Staff'),
    ('AL', 'Alumni'),
    ('O', 'Others')
)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.png', upload_to='profile_pics')
    dob = models.DateField(default=datetime.date.today, verbose_name="DOB")
    communication_addr = models.TextField(verbose_name="Address", blank=True)
    mobile_no = models.CharField(max_length=15, blank=True)
    hide_addr = models.BooleanField(default=False, help_text="Hides Address and phone number")
    batch_year = models.IntegerField(default=current_year, verbose_name='Batch Year', help_text='Pass out year')
    department = models.CharField(default="GEN", choices=dept_choice, max_length=100)
    course = models.CharField(default="O", choices=course_choice, max_length=100, help_text="Ongoing")

    def __str__(self):
        return f'{self.user.username} profile'

    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height >300 or img.width >300:
            output_size = (300,300)
            img.thumbnail(output_size)
            img.save(self.image.path)

user_auth/views.py
from django.shortcuts import render, HttpResponse, render_to_response, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.mail import BadHeaderError, send_mail, EmailMessage
from django.contrib.auth.decorators import login_required
from .models import *
# Create your views here.
from django.template import RequestContext


def home(request):
    if not request.user.is_authenticated:
        return render(request, 'login/login_home.html')
    else:
        return render(request, 'login/home.html')


def auth(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        # Redirect to a success page.
        # print("here")
        return redirect('/')
    else:
        # Return an 'invalid login' error message.
        return redirect('/')


@login_required
def logged_in(request):
    return redirect('/forum')


@login_required
def log_out(request):
    logout(request)
    return redirect('/')


def error_404(request, *args, **argv):
    response = render_to_response('error/error_404.html', {'data': 400})
    response.status_code = 404
    return response


def send_email(request):
    # subject = "Hey there"  # request.POST.get('subject', '')
    # message = "How are you?"  # request.POST.get('message', '')
    # from_email = "dkowsikpai@gmail.com"  # request.POST.get('from_email', '')
    # if subject and message and from_email:
    #     try:
    #         send_mail(subject, message, from_email, ['dkowsikpai@gmail.com'])
    #     except BadHeaderError:
    #         return HttpResponse('Invalid header found.')
    #     return HttpResponse('Sent')
    # else:
    #     # In reality we'd use a form class
    #     # to get proper validation errors.
    #     return HttpResponse('Make sure all fields are entered and valid.')

    message = "hey there"
    mail_subject = 'Activate your blog account.'
    to_email = "dkowsikpai@gmail.com"
    email = EmailMessage(mail_subject, message, to=[to_email], from_email="dkowsikpai.coder@gmail.com")
    email.send()
    return HttpResponse('success')


@login_required
def profile(request, username):
    db = Profile.objects.get(user=User.objects.get(username=username))
    return render(request, 'profile.html', {'data': db})

user_auth/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<link rel="stylesheet" href='{% static "css/bootstrap.min.css" %}'/>
<link rel="stylesheet" href='{% static "css/boot.css" %}'/>
<link rel="stylesheet" href='{% static "css/styles.min.css" %}'/>
<link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.png' %}"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">

{#    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:300,400,700">#}
{#    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">#}
{#    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pikaday/1.6.1/css/pikaday.min.css">#}

<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/boot.js' %}"></script>
{#<script type="text/javascript" src="{% static 'js/theme.js' %}"></script>#}
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>

<style type="text/css">
    .bk_btn{
        cursor: pointer;
    }
</style>

<script type="text/javascript" >
    $(document).ready(function () {
        $('.bk_btn').on('click', function () {
            //alert('here');
            window.location.href = "{% url 'home' %}";
        });
    });
</script>

<head>
    <meta charset="UTF-8">
    <title>syscodifier</title>
</head>

<body class="">
{#   <nav class="navbar navbar-dark navbar-expand-md" id="app-navbar">#}
{#        <div class="container-fluid"><a class="navbar-brand" href="#"><i class="icon ion-ios-infinite" id="brand-logo"></i></a><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>#}
{#            <div#}
{#                class="collapse navbar-collapse" id="navcol-1">#}
{#                <ul class="nav navbar-nav ml-auto">#}
{#                    <li class="nav-item" role="presentation"><a class="nav-link active" href="#">First Item</a></li>#}
{#                    <li class="nav-item" role="presentation"><a class="nav-link" href="#">Second Item</a></li>#}
{#                    <li class="nav-item" role="presentation"><a class="nav-link" href="">Third Item</a></li>#}
{#                </ul>#}
{#        </div>#}
{#        </div>#}
{#    </nav>#}



{#<nav class="navbar navbar-expand-lg navbar-dark bg-dark">#}
{#    <a class="navbar-brand" href="#">Navbar</a>#}
{#    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">#}
{#        <span class="navbar-toggler-icon"></span>#}
{#    </button>#}
{##}
{#    <div class="collapse navbar-collapse" id="navbarSupportedContent">#}
{#        <ul class="navbar-nav mr-auto">#}
{#            <li class="nav-item active">#}
{#                <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>#}
{#            </li>#}
{#            {% if user.is_authenticated %}#}
{#                <li class="nav-item dropdown">#}
{#                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">#}
{#                        GEC Projects#}
{#                    </a>#}
{#                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">#}
{#                        <a class="dropdown-item" href="{% url 'forum' %}">All Projects</a>#}
{#                        <a class="dropdown-item" href="{% url 'reg-project' %}">Register Project</a>#}
{#                    </div>#}
{#                </li>#}
{#                <li class="nav-item dropdown">#}
{#                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">#}
{#                        Settings#}
{#                    </a>#}
{#                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">#}
{#                        <a class="dropdown-item" href="{% url 'profile' user.username %}">User Profile</a>#}
{#                        <a class="dropdown-item" href="#">Change Password</a>#}
{#                        <a class="dropdown-item" href="{% url 'log_out' %}">Logout</a>#}
{#                    </div>#}
{#                </li>#}
{#                <li class="nav-item">#}
{#                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>#}
{#                </li>#}
{#                </ul>#}
{##}
{#            {% else %}#}
{#                <li class="nav-item active">#}
{#                    <a class="nav-link" href="{% url 'home' %}">Login<span class="sr-only">(current)</span></a>#}
{#                </li>#}
{#            {% endif %}#}
{#    </div>#}
{#</nav>#}


{#    <nav class="navbar navbar-dark navbar-expand-lg fixed-top bg-white portfolio-navbar gradient">#}
{#        <div class="container"><a class="navbar-brand logo" href="#">Brand</a><button data-toggle="collapse" class="navbar-toggler" data-target="#navbarNav"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>#}
{#            <div class="collapse navbar-collapse"#}
{#                id="navbarNav">#}
{#                <ul class="nav navbar-nav ml-auto">#}
{#                    {% if user.is_authenticated %}#}
{#                    <li class="nav-item" role="presentation">#}
{#                        <a class="nav-link active" href="#">Home</a>#}
{#                    </li>#}
{#                    <li class="nav-item" role="presentation">#}
{#                        <a class="nav-link" href="{% url 'forum' %}">Projects</a>#}
{#                    </li>#}
{#                    <li class="nav-item" role="presentation">#}
{#                        <a class="nav-link" href="#">CV</a>#}
{#                    </li>#}
{#                    <li class="nav-item" role="presentation">#}
{#                        <a class="nav-link" href="#">Hire me</a>#}
{#                    </li>#}
{#                        <li class="nav-item dropdown">#}
{#                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">#}
{#                            Settings#}
{#                        </a>#}
{#                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">#}
{#                            <a class="dropdown-item" href="{% url 'profile' %}">User Profile</a>#}
{#                            <a class="dropdown-item" href="#">Change Password</a>#}
{#                            <a class="dropdown-item" href="{% url 'log_out' %}">Logout</a>#}
{#                            <div class="dropdown-divider"></div>#}
{#                            <a class="dropdown-item" href="#">Something else here</a>#}
{#                        </div>#}
{#                    </li>#}
{#                    {% else %}#}
{##}
{#                    {% endif %}#}
{#                </ul>#}
{#            </div>#}
{#        </div>#}
{#    </nav>#}


<div id="main_cont" class="container col-xl-12 col-sm-12 col-lg-12">
    {% block content %}{% endblock content %}
</div>
{#<script type="text/javascript">#}
{#    $(document).on('click', '.nav-item li', function() {#}
{#       $(".nav-item li").removeClass("active");#}
{#       $(this).addClass("active");#}
{#   });#}
{#</script>#}
</body>
</html>

user_auth/templates/profile.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    <link href="https://fonts.googleapis.com/css?family=Montserrat|Noto+Sans|Open+Sans|Source+Sans+Pro&display=swap" rel="stylesheet">
    {#{{ data.get_department_display }}#}

    <div class="container-fluid">
        <div class="row m-3">
            <img src="{% static 'images/bk_btn.png' %}" height="40px" width="40px" class="bk_btn"/>
        </div>
    </div>

    <div class="container-fluid p-0 m-0">
        <div class="row m-2">
            <small class="text-muted">Settings / User Profile /</small>
        </div>
        <div class="row mt-3">
            <img class="rounded-circle mx-auto d-block" src="{{ data.image.url }}" width="200px" height="200px"/>
        </div>
        <div class="row mt-1 ">
            <h3 style="font-family: 'Noto Sans', sans-serif;" class="mx-auto d-block">{{ data.user.first_name }} {{ data.user.last_name }}</h3>
        </div>
        <div class="row m-3" style="text-align: center">
            <div class="col-md-3 col-sm-3 col-lg-3 mx-auto d-block" style="border-right: rgba(108,117,125,0.72) 1px solid;">
                <img class="rounded-circle mx-auto" src="{% static 'images/profile/dept.png' %}" width="100px" height="100px"/><br>
                <h3 style="font-family: 'Open Sans', sans-serif;" class="mx-auto d-block">{{ data.get_department_display }}</h3>
            </div>
            <div class="col-md-3 col-sm-3 col-lg-3 mx-auto d-block" style="border-right: rgba(108,117,125,0.72) 1px solid;">
                <img class="rounded-circle mx-auto d-block" src="{% static 'images/profile/award.png' %}" width="100px" height="100px"/><br>
                <h3 style="font-family: 'Open Sans', sans-serif;" class="mx-auto d-block">{{ data.get_course_display }}</h3>
            </div>
            {% if not data.hide_addr %}
                {% if data.communication_addr or data.mobile_no %}
                    <div class="col-md-3 col-sm-3 col-lg-3 mx-auto d-block" style="border-right: rgba(108,117,125,0.72) 1px solid;">
                        <img class="rounded-circle mx-auto d-block" src="{% static 'images/profile/edu.png' %}" width="100px" height="100px"/><br>
                        <h3 style="font-family: 'Open Sans', sans-serif;" class="mx-auto d-block">Batch of {{ data.batch_year }}</h3>
                    </div>
                    <div class="col-md-3 col-sm-3 col-lg-3 mx-auto d-block">
                        <img class="rounded mx-auto d-block" src="{% static 'images/profile/location.png' %}" width="100px" height="100px"/><br>
                        {% if data.communication_addr %}
                            <h3 style="font-family: 'Open Sans', sans-serif;" class="mx-auto d-block">
                                <img src="{% static 'images/profile/house.png' %}" width="30px" height="30px"/>
                                {{ data.communication_addr }}
                            </h3>
                        {% endif %}
                        {% if data.mobile_no %}
                            <h3 style="font-family: 'Open Sans', sans-serif;" class="mx-auto d-block">
                                <img src="{% static 'images/profile/phone.png' %}" width="30px" height="30px"/>
                                {{ data.mobile_no }}
                            </h3>
                        {% endif %}
                    </div>
                {% endif %}
            {% else %}
                <div class="col-md-3 col-sm-3 col-lg-3 mx-auto d-block">
                    <img class="rounded-circle mx-auto d-block" src="{% static 'images/profile/edu.png' %}" width="100px" height="100px"/><br>
                    <h3 style="font-family: 'Open Sans', sans-serif;" class="mx-auto d-block">Batch of {{ data.batch_year }}</h3>
                </div>
            {% endif %}
        </div>
        <div class="row">

        </div>
    </div>
{% endblock content %}